/*
$(document).ready(function(){
    $('span').hover(
        function(){
            $(this).fadeTo('slow',0.1);
        },
        function(){
            $(this).fadeTo('slow',1);
        }     
    ); 
});
*/